#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR=${DIR}/..

setup_nginx() {
  echo "⚙️ Running dev-nginx setup"
  brew tap guardian/homebrew-devtools
  brew install guardian/devtools/dev-nginx

  dev-nginx setup-app "$ROOT_DIR"/nginx/nginx-mapping.yaml
  dev-nginx restart-nginx
  echo "✅ dev-nginx setup complete"
}

npm_install() {
  echo "⚙️ Running npm install"
  pushd collab
  npm i
  popd
  echo "✅ npm install complete"
}

setup_postgres() {
  echo "⚙️ Running postgres setup"
  docker-compose up -d
  pushd collab
  npm run database-migration
  popd
  echo "✅ postgres setup complete"
}

setup_nginx
npm_install
setup_postgres